### ISSUE TITLE
Where & How can I test my docker file or image?

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/Dockerflow#9]
I think I've made a dockerfile (and image) conforming to Dockerflow requirements. Where can I build/deploy it to test that it's working?

**Comment by lmorchard** [comment]
FWIW, you should be able to build & test it on your local machine using docker. Beyond that, you can create a `circle.yml` in your branch, enable CircleCI for your fork, and see what happens. 

[Here's what our `circle.yml` looks like for Test Pilot, right now.](https://github.com/mozilla/testpilot/blob/master/circle.yml) You *probably* don't need all the node/npm stuff, since we use that to build frontend assets rather than Django's builtin stuff

**Comment by groovecoder** [comment]
I have it running locally with Docker, and I have a Deis cluster building it from the Dockerfile and running it on AWS too.

I don't fully understand the way Dockerflow and AWS run ... I assumed there would be some kind of cloudformation template or something that I could set up in the sandbox IAM and try running my app there the same way it will run in stage/prod?

**Comment by lmorchard** [comment]
> I don't fully understand the way Dockerflow and AWS run ... I assumed there would be some kind of cloudformation template or something that I could set up in the sandbox IAM and try running my app there the same way it will run in stage/prod?

Good question. We're not doing any of that for Test Pilot, so far :)

**Comment by mostlygeek** [comment]
> I don't fully understand the way Dockerflow and AWS run ... I assumed there would be some kind of cloudformation template or something that I could set up in the sandbox IAM and try running my app there the same way it will run in stage/prod?

One of the core design goals of Dockerflow is that you shouldn't have to be concerned about how the hosting service runs your container if you follow the spec. 

A few people are using Docker compose on dev machines to pull in things like a database, redis, etc. Unless you have to use an AWS service (SQS, SNS, etc) then you don't need to worry about creating an IAM role for EC2 box.
